app:
  name: dijonamic-bot

pvc:
  name: dijonamic-data
  size: 250Mi
  storageClass: "" # leave empty to use the kubernetes cluster's default

secrets:
  name: dijonamic-secrets # must exist in the release namespace with key `discord_token`

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    enabled: false # Liveness check isn't working at the moment and continuously restarts the container, must diagnose
    initialDelaySeconds: 10
    periodSeconds: 20
